[project]
name = "titanoboa"
version = "0.1.6"
description = "Experimental Vyper interpreter"
#authors = []
license = { file = "LICENSE" }
readme = "README.md"
#homepage = "https://github.com/vyperlang/titanoboa"
#repository = "https://github.com/vyperlang/titanoboa"
#documentation =

keywords = ["ethereum", "evm", "smart contract", "development"]

classifiers = ["Topic :: Software Development"]

# Requirements
dependencies = [
    "vyper @ git+https://github.com/vyperlang/vyper.git@1cfeabb7e122a5c476dccb8fc55e8fe0b91cdf2c",
    "eth-stdlib",
    "eth-abi",
    "py-evm",
    "eth-typing",
    "hypothesis",
    "pytest",
    "rich",

    # required for forking:
    "requests",
]

[project.optional-dependencies]
forking-recommended = ["plyvel", "ujson"]

[build-system]
requires = ["setuptools", "wheel"]

[tool.setuptools.packages.find]
include = ["boa*"]

[tool.pytest.ini_options]
markers = ["ignore_isolation: Do not preserve state during tests"]

#[dev-dependencies]
#black = { version = "^18.3-alpha.0", python = "^3.6" }
