name: unitary

on: ["push", "pull_request"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  unitary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    name: "tests: Python ${{ matrix.python-version }}"

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install Requirements
        run: |
          pip install -r dev-requirements.txt
          pip install .

      - name: Run Tests (except those which require anvil)
        run: |
          pytest -n auto \
            --ignore tests/integration/network/anvil \
            --ignore tests/integration/network/sepolia
        env:
          MAINNET_ENDPOINT: ${{ secrets.ALCHEMY_MAINNET_ENDPOINT }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run Networked Tests against anvil
        run: pytest -n auto tests/integration/network

      - name: Run Sepolia Tests
        # disable xdist, otherwise they can contend for tx nonce
        run: pytest -n 0 tests/integration/sepolia
        env:
          SEPOLIA_ENDPOINT: ${{ secrets.ALCHEMY_SEPOLIA_ENDPOINT }}
          SEPOLIA_PKEY: ${{ secrets.SEPOLIA_PKEY }}
